"""empty message

Revision ID: ffe6f1595fe7
Revises: d3551f5737d1
Create Date: 2023-02-10 20:50:22.743633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe6f1595fe7'
down_revision = 'd3551f5737d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(length=480), nullable=False))
    op.add_column('user', sa.Column('nombre', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('apellido', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('salt', sa.String(length=250), nullable=False))
    op.drop_column('user', 'password')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('user', 'salt')
    op.drop_column('user', 'apellido')
    op.drop_column('user', 'nombre')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
